"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FilterOperators = exports.TransformJoinResultTypes = void 0;
var TransformJoinResultTypes;
(function (TransformJoinResultTypes) {
    TransformJoinResultTypes[TransformJoinResultTypes["SINGLE"] = 0] = "SINGLE";
    TransformJoinResultTypes[TransformJoinResultTypes["MULTI"] = 1] = "MULTI";
})(TransformJoinResultTypes = exports.TransformJoinResultTypes || (exports.TransformJoinResultTypes = {}));
var FilterOperators;
(function (FilterOperators) {
    FilterOperators["eq"] = "eq";
    FilterOperators["orEq"] = "orEq";
    FilterOperators["gt"] = "gt";
    FilterOperators["orGt"] = "orGt";
    FilterOperators["lt"] = "lt";
    FilterOperators["orLt"] = "orLt";
    FilterOperators["gte"] = "gte";
    FilterOperators["orGte"] = "orGte";
    FilterOperators["lte"] = "lte";
    FilterOperators["orLte"] = "orLte";
    FilterOperators["in"] = "in";
    FilterOperators["orIn"] = "orIn";
    FilterOperators["notIn"] = "notIn";
    FilterOperators["orNotIn"] = "orNotIn";
    FilterOperators["contains"] = "contains";
    FilterOperators["orContains"] = "orContains";
    FilterOperators["startWith"] = "startWith";
    FilterOperators["orStartWith"] = "orStartWith";
    FilterOperators["endWith"] = "endWith";
    FilterOperators["orEndWith"] = "orEndWith";
    FilterOperators["not"] = "not";
    FilterOperators["orNot"] = "orNot";
    FilterOperators["regex"] = "regex";
    FilterOperators["orRegex"] = "orRegex";
    FilterOperators["isNull"] = "isNull";
    FilterOperators["orIsNull"] = "orIsNull";
    FilterOperators["isNotNull"] = "isNotNull";
    FilterOperators["orIsNotNull"] = "orIsNotNull";
    FilterOperators["isTrue"] = "isTrue";
    FilterOperators["orIsTrue"] = "orIsTrue";
    FilterOperators["isFalse"] = "isFalse";
    FilterOperators["orIsFalse"] = "orIsFalse";
    FilterOperators["group"] = "group";
    FilterOperators["orGroup"] = "orGroup";
})(FilterOperators = exports.FilterOperators || (exports.FilterOperators = {}));
